### ISSUE TITLE
Poids des images et releases pdf/epub/mobi

### ISSUE THREAD

**Issue by s-kocher** [progit/progit2-fr#108]
Bonjour,

je constate une grande différence entre le poids des exports PDF/Mobi/Epub entre la version anglaise et française.

Format	: fichier FR vs EN
epub	: 34.8 MB vs 5.73 MB
mobi	: 59 MB vs 9.3 MB
pdf		: 35.6 MB vs 11.8 MB

Dossiers images : 39 MB vs 4MB

Cela semble lié aux images, après quelques comparaisons des ressources FR/EN, il s'avère que les PNG français utilisent un jeu de couleur sur 32 bits alors que les images anglaise sont en 8 bits.

En sauvegardant une image fr en 8 bits (test avec paint.net), on redescend bien à un ordre de grandeur similaire.

Vu la relative simplicité des schémas, 256 couleurs (8 bits) doivent être largement suffisant (comme l'atteste les schémas anglais) et cela permettrait probablement d'alléger considérablement le poids des releases notamment pour les formats "mobiles" epub/mobi.

https://superuser.com/questions/246877/bulk-convert-png-24-to-png-8-files-with-best-quality
Quelques pistes pour la conversion en masse des png

**Comment by jnavila** [comment]
En fait, les images d'origine ont subi une cure d'amaigrissement ici:

https://github.com/progit/progit2/commit/bb9e9276e94bdb61815cdfeeabbf9cebf0814d0e

Les images n'ont pas été traduites, donc on peut les recopier depuis le répo d'origine. L'occasion d'ouvrir une pull-request ?
