### ISSUE TITLE
"Personnalisation de Git - Configuration de Git" : autocrlf "introduit en version"

### ISSUE THREAD

**Issue by Chealer** [progit/progit2-fr#126]
La section Formatage et espaces blancs de [la page de configuration](https://git-scm.com/book/fr/v1/Personnalisation-de-Git-Configuration-de-Git) contient ce qui suit sur core.autocrlf :

> Si vous utilisez un système Linux ou Mac qui utilise les fins de ligne LF, vous ne souhaitez sûrement pas que Git les convertisse automatiquement lorsque vous extrayez des fichiers. Cependant, si un fichier contenant des CRLF est accidentellement introduit en version, vous souhaitez que Git le corrige .

La deuxième phrase est brisée. « accidentellement introduit en version » devrait sans doute être soit « accidentellement introduit » ou « accidentellement versionné ».

Notez qu'il y a également un espace superflu avec le point.

**Comment by aollier** [comment]
Une petite remarque : l'adresse que vous utilisez n'est pas la bonne, c'est la version 1 de progit. La version 2 de progit en français se trouve [à cette adresse](https://git-scm.com/book/fr/v2) et la page de configuration [à celle-là](https://git-scm.com/book/fr/v2/Personnalisation-de-Git-Configuration-de-Git).
Ceci dit, cette formule est également présente dans la version 2.

**Comment by aollier** [comment]
@jnavila Qu'en penses-tu ?

**Comment by jnavila** [comment]
"introduit en gestion de version" ?

**Comment by Chealer** [comment]
Merci pour la remarque @aollier (mais c'est ici qu'on se retrouve actuellement en suivant le processus de signalement).

"introduit en gestion de version" est sans doute ce que l'auteur avait l'intention d'écrire. Cela dit, "introduit dans le dépôt" serait aussi clair, et puisque le contexte rend évident qu'il est question du dépôt et que cette phrase n'est indicative, "introduit" suffit. C'est d'ailleurs ce qui correspond à la version originale.

**Comment by jnavila** [comment]
Est-ce plus compréhensible de réduire la phrase ? Je ne suis pas dogmatique. Proposez votre correction avec une PR. Merci.

**Comment by Chealer** [comment]
Au plan de la compréhensibilité, je ne sais pas si soit "introduit en gestion de version" ou "introduit" est vraiment meilleur. Je ne maîtrise pas la terminologie dans ce domaine.
Mais il me semble que si "introduit en gestion de version" est choisi, "version" devrait être au pluriel. C'est au moins l'usage sur Wikipédia en tout cas : https://fr.wikipedia.org/wiki/Gestion_de_versions
