### ISSUE TITLE
Coquille p27

### ISSUE THREAD

**Issue by freMea** [progit/progit2-fr#150]
v2.1.65 du pdf
![image](https://user-images.githubusercontent.com/22337329/118669290-ee6e2b00-b7f5-11eb-831f-e3fbefb38965.png)

**Comment by jnavila** [comment]
Merci de cette relecture. Une petite requête de tirage ?

**Comment by freMea** [comment]
C’est fait. Ça s’est avéré plutôt simple. En lisant vite,  j’avais pensé qu’il eût fallu que je génère le livre pour pouvoir le modifier. C’était absurde de ma part.
