### ISSUE TITLE
Chapitre 7 Lien en erreur (500)

### ISSUE THREAD

**Issue by dcpc007** [progit/progit2-fr#27]
http://git-scm.com/book/fr/v2/Git-Tools-Revision-Selection
Les liens vers la "Figure 7-1" renvoie sur une page d'erreur 500
Lien supposé être http://git-scm.com/book/fr/v2/ch00/double_dot

(dsl si le format pour l'issue n'est pas correct, n'hésitez pas à me corriger)

**Comment by dcpc007** [comment]
A priori la plupart des liens vers images semblent pointer vers une donnée inexistante (avec page 500)
vu par ex dans Chapitre 3 sur les branches avec les liens vers les figures.

**Comment by jnavila** [comment]
En fait, cette arrive aussi sur la version anglaise. C'est un des nombreux bugs du script de déploiement des livres sur le site git-scm.com. La génération des pdfs et ebooks fonctionne correctement en local, ce qui signifie que les liens sont corrects dans le source.

Le mieux reste d'ouvrir un ticket sur https://github.com/git/git-scm.com
