### ISSUE TITLE
Chap 3 / Rebasing : Typo 

### ISSUE THREAD

**Issue by dcpc007** [progit/progit2-fr#28]
Typo dans le paragraphe "Rebaser quand vous rebasez"

Appliquer ces commits au sommet de esuipe1/master
-> Appliquer ces commits au sommet de equipe1/master

**Comment by jnavila** [comment]
Merci. Si vous avez d'autres corrections, pourriez-vous faire un fork du dépôt et ouvrir une requête de tirage ?

Merci

**Comment by dcpc007** [comment]
Ok merci, il va falloir que je m'y mette pour voir comment on fait ça, j'ai pas encore beaucoup utilisé git, et encore moins github
