### ISSUE TITLE
Modification des marges pdf pour print (gâchis)

### ISSUE THREAD

**Issue by dcpc007** [progit/progit2-fr#71]
Bonjour,

Issue ouverte aussi sur le projet en/us d'origine.

Est-il possible d'avoir ou de générer un pdf mais sans les marges blanches horribles qui mangent une place énorme pour rien sur les pages ?
Je dirais qu'on doit facilement pourvoir rogner 1cm de chaque côté et plus pour la marge de reliuer (gauche/droite) et donc réduire assez fortement le nombre de pages sans réduire la lisibilité.

Actuellement il doit y avoir au moins 25% de largeur A4 pour les marge :-(

Le but quand même : pour les utilisateurs, j'aimerais imprimer certaines parties, mais voudrait éviter de gâcher trop de feuilles pour ça.
De toute façon même si c'était pour un livre relié la place est vraiment gâchée. D'ailleurs tous les schémas eux sont en pleine largeur ... illogique si les marges étaient là pour la lisibilité (du genre avec une reliure collée au centre et un livre qui ne s'ouvre pas à 180°).
Merci d'avance.

**Comment by jnavila** [comment]
On peut faire un pdf à partir du code source. Actuellement, le pdf généré ne prend pas en compte les liens intra-document, mais si c'est pour imprimer, ça ne doit pas poser de problème. Pour la génération du pdf, je n'ai pas regardé la gestion des marges, mais tout est en local, donc bidouillable.

**Comment by deild** [comment]
il est possible de les réduire en définissant un thème en remplacement de [default-theme.yml](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml)

il suffit par exemple de les redéfinir comme ci-dessous :
```
page:
  background_color: ffffff
  layout: portrait
  margin: [13mm, 13mm, 13mm, 13mm]
  margin_inner: 0.20mm
  margin_outer: 0.15mm
  size: A4
```
vous pouvez utiliser [custom-theme.txt](https://github.com/progit/progit2-fr/files/921991/custom-theme.txt) en le renommant custom-theme.yml dans le répertoire `theme`puis généré le pdf avec la commande `bundle exec asciidoctor-pdf progit.asc -a pdf-style=theme/custom-theme.yml 2>/dev/null` 

Bonne impression.

**Comment by jnavila** [comment]
Les dernières version d'asciidoc-pdf ont une mise en page plutôt équilibrée. Un système de compilation automatique permet d'accéder aux pdfs des dernières versions [ici](https://github.com/progit/progit2-fr/releases)

**Comment by dcpc007** [comment]
Yeah, thx, very very better now !!!!

I'll look for the reprint in a "2 page per sheet" tomorrow.
