### ISSUE TITLE
Problème dans le menu du livre ProGit fr ?

### ISSUE THREAD

**Issue by boissonnfive** [progit/progit2-fr#82]
Bonjour,

tout d'abord bravo pour votre travail de traduction.

Le problème : la version en ligne sur Git Book (https://gitbookio.gitbooks.io/progit/content/fr/index.html) n'affiche pas dans son menu une table des matières correcte. Le chapitre 1 correspond au chapitre 8. Le chapitre 7 au chapitre 1. Le chapitre 6 devrait être GiHub, mais est "UtilitairesGit" ... Liste non exhaustive.
J'ai vérifié sur la version anglaise, et pas de problème similaire.

Est-ce que ça peut/doit être corrigé ?

**Comment by jnavila** [comment]
Bonjour,

Je ne savais pas qu'il y avait une édition en ligne de Progit ailleurs que sur git-scm.com. Le livre s'édite correctement dans notre cas, donc cela vient de la chaîne d'édition.  Nous ne sommes pas responsable de la chaîne d'édition sur ce site. 

Selon l'avertissement en bas de première page, c'est sur le projet AaronO/progit-to-gitbook qu'il faut remonter ce bug.
