### ISSUE TITLE
Images manquantes

### ISSUE THREAD

**Issue by vinylourson** [progit/progit2-fr#98]
Dans les pages que j'ai visitées, les images d'illustration sont manquantes (fichiers non trouvés)

exemples : 
* https://github.com/progit/progit2-fr/blob/master/book/05-distributed-git/sections/images/benevolent-dictator.png 

ou encore 

* https://github.com/progit/progit2-fr/blob/master/book/05-distributed-git/sections/images/small-team-6.png

**Comment by jnavila** [comment]
C'est normal. les sections sont incluses dans un document maître et les références aux images se font relativement à ce document maître. Pour avoir une version web du livre, il suffit d'aller sur https://git-scm.com/book/fr
